AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: ETL for Social System User Index.
Resources:
  s3Stats:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: statsApp.lambda_handler
      Runtime: python3.7  
      CodeUri: s3Stats/
      Description: ''
      MemorySize: 128
      Timeout: 60
      Role: >-
        arn:aws:iam::904705273474:role/service-role/s3-post-ingester-role-rv5h3u2k